// pool.gen.go
// Code generated by pool generator. DO NOT EDIT.

package pool

import (
	"sync"
)

// Resetter defines the interface for types that can be reset to their zero state
type Resetter interface {
	Reset()
}

// Pool is a generic pool of objects that can be reset.
// T must be a type that implements the Reset() method.
type Pool[T Resetter] struct {
	pool sync.Pool
}

// New creates a new Pool for type T.
// The constructor function is used to create new instances when the pool is empty.
func New[T Resetter](constructor func() T) *Pool[T] {
	return &Pool[T]{
		pool: sync.Pool{
			New: func() any {
				return constructor()
			},
		},
	}
}

// Get returns an object from the pool.
// If the pool is empty, a new object is created using the constructor.
// The returned object is guaranteed to be in its zero state (after Reset() has been called).
func (p *Pool[T]) Get() T {
	obj := p.pool.Get().(T)
	obj.Reset()
	return obj
}

// Put returns an object to the pool.
// The object is reset before being stored to ensure it's clean for future use.
func (p *Pool[T]) Put(obj T) {
	obj.Reset()
	p.pool.Put(obj)
}

// PoolStats represents statistics about the pool's usage.
// This is exposed for monitoring and debugging purposes.
type PoolStats struct {
	// NewCalls counts how many times the constructor was called
	NewCalls int64
}

// GetStats returns usage statistics for the pool.
// Note: This requires custom instrumentation and is not provided by sync.Pool.
func (p *Pool[T]) GetStats() PoolStats {
	// sync.Pool doesn't expose statistics, so this is a placeholder
	// In a real implementation, you might want to add atomic counters
	return PoolStats{}
}
